# Generated by Django 4.0.1 on 2022-01-19 00:58

from django.db import migrations

def load_data(apps, schema_editor):
    Category = apps.get_model('store', 'Category')
    Product = apps.get_model('store', 'Product')

    category_one = Category.objects.create(
        name='Category 1', description='This is category 1')
    
    category_two = Category.objects.create(
        name='Category 2', description='This is category 2')

    Product.objects.create(
        name='Product 1', description='This is product 1', 
        image='https://via.placeholder.com/300.png?text=Product1', 
        category=category_one)

    Product.objects.create(
        name='Product 2', description='This is product 2', 
        image='https://via.placeholder.com/300.png?text=Product2', 
        category=category_two)

class Migration(migrations.Migration):

    dependencies = [
        ('store', '0001_initial'),
    ]

    operations = [
        migrations.RunPython(load_data),
    ]
